### ISSUE TITLE
VersionCRD定义

### ISSUE THREAD

**Issue by cuisongliu** [labring-actions/runtime-ctl#1]
```
spec:
  config:
      cri: docker
      runtime: k8s
      runtimeVersion: 1.23.6,1.23,1.23.0
      step: dev/release
  default:
      containerd: 1.5.0
      docker: 1.5.0
      cri-docker: 1.5.0
      sealos: 4.1.5-rc1
      crio: 1.2.0
      crio-crun: 1.0.0
      k8s: 
         containerd: 1.5.0
         docker: 1.5.0
         cri-docker: 1.5.0
         sealos: main
         crio: 1.2.0
         crio-crun: 1.0.0

```

**Comment by cuisongliu** [comment]
1.26起cri-dockerd需要v0.3.x
crio需要k8s是1.20起

**Comment by cuisongliu** [comment]
<img width="1147" alt="image" src="https://user-images.githubusercontent.com/4150905/219952062-25f07932-733b-47be-b0d1-1c879fbee405.png">

**Comment by cuisongliu** [comment]
![image](https://user-images.githubusercontent.com/4150905/219952165-0edc0429-7054-4d59-9903-faf9c8c436fb.png)

**Comment by muicoder** [comment]
`default.yaml` content:
```yaml
default:
  containerd: 1.6.0
  docker: 23.0.0
  cri-dockerd: 0.3.0
  sealos: 4.1.4
  crio: 1.26.0
  crun: 1.6
  runc: 1.1.0
```
`config.yaml` content:
```yaml
config:
  cri:
    - docker
    - containerd
    - crio
  runtime: k8s
  runtimeVersion:
    - 1.22
    - 1.26
```
Target content:
===
```yaml
include:
  - cri: docker
    version: 20.10
    container-runtime: runc
    container-runtimeVersion: 1.1.4
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.22.17
  - cri: docker
    version: 23.0.1
    container-runtime: runc
    container-runtimeVersion: 1.1.4
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.26.1
  - cri: containerd
    version: 1.6.18
    container-runtime: runc
    container-runtimeVersion: 1.1.4
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.22.17
  - cri: containerd
    version: 1.6.18
    container-runtime: runc
    container-runtimeVersion: 1.1.4
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.26.1
  - cri: crio
    version: 1.22.5
    container-runtime: crun
    container-runtimeVersion: 1.8
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.22.17
  - cri: crio
    version: 1.26.1
    container-runtime: crun
    container-runtimeVersion: 1.8
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.26.1
```

**Comment by cuisongliu** [comment]
```
include:
  - criType: docker
    criVersion: 20.10
    criDockerd: 3.x.x
    criRuntime: runc
    criRuntimeVersion: 1.1.4
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.22.17
```

**Comment by cuisongliu** [comment]
```
default:
  containerd: 1.6.16
  docker: 20.10
  cri-docker-v2: v0.3.1
  cri-docker-v3: v0.2.6
  sealos: v4.1.5-rc1
  crio: v1.26.1
  crun: 1.8
  runc: v1.1.4
```
