### ISSUE TITLE
输出根据cri调整对应的数据

### ISSUE THREAD

**Issue by cuisongliu** [labring-actions/runtime-ctl#4]
```
include:
  - criType: docker
    criVersion: 20.10
    criDockerd: 3.x.x
    criRuntime: runc
    criRuntimeVersion: 1.1.4
    sealos: 4.1.5
    runtime: k8s
    runtimeVersion: 1.22.17
```
