### ISSUE TITLE
输入格式调整

### ISSUE THREAD

**Issue by cuisongliu** [labring-actions/runtime-ctl#5]
```
version:
  containerd: 1.6.16
  docker: 20.10
  sealos: 4.1.5-rc1
  crun: 1.8
  runc: 1.1.4
```
